---
- name: Install latest IDE for Linux
  hosts: all
  gather_facts: false

  tasks:
    - name: Download Bitwarden .deb package
      ansible.builtin.get_url:
        url: "https://vault.bitwarden.com/download/?app=desktop&platform=linux&variant=deb"
        dest: /tmp/bitwarden.deb
        mode: '0644'
      become: yes

    - name: Install Bitwarden Desktop
      apt:
        deb: /tmp/bitwarden.deb
        state: present
      become: yes

    - name: Clean up downloaded .deb
      file:
        path: /tmp/bitwarden.deb
        state: absent
      become: yes
