---
- name: Install latest IDE for Linux
  hosts: all
  gather_facts: false

  tasks:
    - name: Install Bitwarden
      ansible.builtin.shell: |
        wget -qO- https://downloads.bitwarden.com/linux/debian/bitwarden-release-key.gpg | gpg --dearmor | sudo tee /usr/share/keyrings/bitwarden-archive-keyring.gpg > /dev/null
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bitwarden-archive-keyring.gpg] https://downloads.bitwarden.com/linux/debian stable main" | sudo tee /etc/apt/sources.list.d/bitwarden.list
        sudo apt-get update && sudo apt-get install -y bitwarden
