---
- name: Install latest GoLand IDE for Linux
  hosts: all
  gather_facts: false

  tasks:
    - name: Get latest GoLand release info
      uri:
        url: "https://data.services.jetbrains.com/products/releases?code=GO&latest=true&type=release"
        return_content: yes
      register: goland_release
      changed_when: false
      delegate_to: localhost
      run_once: true

    - name: Extract Linux download URL
      set_fact:
        goland_linux_url: "{{ (goland_release.content | from_json).GO[0].downloads.linux.link }}"
      delegate_to: localhost
      run_once: true

    - name: Extract version from URL
      set_fact:
        goland_version: "{{ goland_linux_url.split('/')[-1].split('.tar.gz')[0].split('goland-')[-1] }}"
      delegate_to: localhost

    - name: Detected latest goland
      debug:
        msg: |
          URL: {{ goland_linux_url }}
          GoLand version: {{ goland_version }}

    - name: Download GoLand
      get_url:
        url: "{{ goland_linux_url }}"
        dest: "/tmp/goland-{{ goland_version }}.tar.gz"
        mode: '0755'
        timeout: 60

    - name: Clean previous installation
      file:
        path: "/opt/GoLand-{{ goland_version }}"
        state: absent
      become: true

    - name: Install GoLand
      become: true
      unarchive:
        src: "/tmp/goland-{{ goland_version }}.tar.gz"
        dest: "/opt/"
        remote_src: yes
        extra_opts: ["--strip-components=1"]
        mode: '0755'

    - name: Cleanup download
      file:
        path: "/tmp/goland-{{ goland_version }}.tar.gz"
        state: absent
