- name: Разрешения для ext
  hosts: all
  gather_facts: true

  tasks:
    - name: Разрешить ext sudo без пароля
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "ext ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
