---
- name: Install latest GoLand IDE for Linux
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Nekoray 4.0.1 AppImage
      block:
        - name: Create AppImages directory
          ansible.builtin.file:
            path: "/home/ext/AppImages"
            state: directory
            owner: ext
            group: ext
            mode: '0755'

        - name: Download Nekoray AppImage
          ansible.builtin.get_url:
            url: "https://github.com/MatsuriDayo/nekoray/releases/download/4.0.1/nekoray-4.0.1-2024-12-12-linux-x64.AppImage"
            dest: "/home/ext/AppImages/nekoray.AppImage"
            owner: ext
            group: ext
            mode: '0755'


        - name: Extract icon from AppImage
          ansible.builtin.command:
            cmd: |
              /home/ext/AppImages/nekoray.AppImage --appimage-extract nekobox.png
              mv squashfs-root/nekobox.png /home/ext/.local/share/icons/hicolor/256x256/apps/nekoray.png
              rm -rf squashfs-root
          args:
            creates: "/home/ext/.local/share/icons/hicolor/256x256/apps/nekoray.png"
          become: no
          changed_when: false

        - name: Create proper desktop entry
          ansible.builtin.copy:
            content: |
              [Desktop Entry]
              Type=Application
              Name=Nekoray
              GenericName=Proxy Client
              Comment=Qt-based cross-platform proxy client
              Exec=/home/ext/AppImages/nekoray.AppImage
              Icon=nekoray
              Terminal=false
              Categories=Network;
              StartupWMClass=nekoray
              X-AppImage-Version=4.0.1
            dest: "/home/ext/.local/share/applications/nekoray.desktop"
            owner: ext
            group: ext
            mode: '0644'
        - name: Update desktop database
          ansible.builtin.command: update-desktop-database /home/ext/.local/share/applications
          become: no

        - name: Update icon cache
          ansible.builtin.command: gtk-update-icon-cache -f /home/ext/.local/share/icons/hicolor
          become: no
