---
docker_required_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - gnupg-agent

docker_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
docker_repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

docker_reboot_required: false
